#%RAML 1.0 NamedExample

flightCancellation:
  bookingID: IND0001
  PNR: 12345678
  flightNumber: 6E-227
  startDate: 23-02-2022
  startTime: 12:15
  origin: CCU
  destination: BEN
  noOfPassengers: 2
  totalAmount: 10000