#%RAML 1.0
title: APISpec-BookMyHoliday-Flights

protocols:
  - HTTP

uses: 
  flightCollection: resourceTypes/flightResources.raml
            
types: 
  Flight: !include datatypes/flightDataType.raml
  FlightBooking: !include datatypes/flightBookingDataType.raml
  FlightBookingResponse: !include datatypes/flightBookingResponseDataType.raml
  FlightCancellation: !include datatypes/flightCancellationDataType.raml

/flights:
  type:
    flightCollection.flightsCollection:
      getFlightsResponse: !include examples/flightsExample.raml
      addFlight: !include examples/flightExample.raml
      cancelFlight: !include examples/flightCancellationExample.raml
  get:
    queryParameters:
      startDate?:
        displayName: Date of Departure
        type: string
        required: false
        example:
          23-02-2022
      origin:
        displayName: Origin
        type: string
        required: true
        example:
          CCU
      destination:
        displayName: Destination
        type: string
        required: true
        example:
          BEN
      noOfPassengers?:
        displayName: No. of Passengers
        type: integer
        minimum: 1
        default: 1
        required: false
        example:
          2
  post:
  
  put:
            
  /{flightID}:
    type:
      flightCollection.flightCollection:
        getSpecificFlight: !include examples/flightExample.raml
        bookFlight: !include examples/flightBookingExample.raml
        flightBookingResponse: !include examples/flightBookingResponseExample.raml
    
    get:
              
    post: